-- Autopilot loops D/E/F
ALTER TYPE "AutopilotLoopKind" ADD VALUE IF NOT EXISTS 'ASSIDUITY';
ALTER TYPE "AutopilotLoopKind" ADD VALUE IF NOT EXISTS 'TOKEN_SAFEGUARD';
ALTER TYPE "AutopilotLoopKind" ADD VALUE IF NOT EXISTS 'DRIFT_GUARD';
