import {
  BookOpen,
  Bot,
  Calendar,
  CalendarClock,
  CalendarDays,
  CreditCard,
  GraduationCap,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  MessageSquare,
  MessagesSquare,
  Music2,
  Rocket,
  Timer,
  UserCheck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { HelpCategoryKey, HelpTopicKey } from "@/lib/help/config";

export const HELP_TOPIC_ICONS: Record<HelpTopicKey, LucideIcon> = {
  gettingStarted: Rocket,
  accueil: UserCheck,
  sessions: LayoutGrid,
  cockpit: LayoutDashboard,
  integrations: CreditCard,
  agentics: Bot,
  enrollmentsWaitlist: Users,
  schedule: Calendar,
  punch: Timer,
  training: BookOpen,
  messages: MessageSquare,
  availability: CalendarClock,
  managerSchedule: Users,
  weekTemplates: LayoutTemplate,
  managerSops: BookOpen,
};

export const HELP_CATEGORY_ICONS: Record<HelpCategoryKey, LucideIcon> = {
  studio: Music2,
  payments: Wallet,
  manage: Users,
  team: MessagesSquare,
  schedule: CalendarDays,
  clock: Timer,
  learning: GraduationCap,
};
