import { AlertTriangle, Clock3, Moon, Sparkles, Sun, X } from "lucide-react";
import { formatTimeRange } from "@/lib/calendar/format";
import { periodStyle } from "@/lib/calendar/style";
import {
  AUTOPILOT_BADGE,
  AUTOPILOT_CAPSULE,
  resolveStationMatrix,
} from "@/lib/design/station-matrix";
import type { ShiftWithEmployee } from "@/lib/data/shifts";
import type { Locale } from "@/lib/i18n/config";
import type { Dictionary } from "@/lib/i18n/dictionaries";
import { stationLabel } from "@/lib/stations/display";
import { UserAvatar } from "@/components/ui/user-avatar";
import { cn } from "@/lib/utils";

/**
 * Floating shift capsule — Fable / Modernist Organic.
 * Station-tinted fill, avatar, badge pill, monospace time.
 * Autopilot / unassigned drafts get a dashed red RSI treatment.
 */
export function ModernShiftCard({
  shift,
  locale,
  dict,
  compact = false,
  draggableHint = false,
  onDelete,
}: {
  shift: ShiftWithEmployee;
  locale: Locale;
  dict: Dictionary;
  compact?: boolean;
  draggableHint?: boolean;
  onDelete?: () => void;
}) {
  const hasAlert = shift.overtimeFlag || shift.restViolationFlag;
  const resolvedPeriod = shift.period ?? "DAY";
  const period = periodStyle[resolvedPeriod];
  const PeriodIcon = resolvedPeriod === "NIGHT" ? Moon : Sun;
  const isDraft = shift.status === "DRAFT";
  const unassigned = !shift.employee;
  /** Dashed red RSI treatment — unassigned / suggested slots only */
  const isAutopilot = unassigned;

  const matrix = resolveStationMatrix(shift.station);
  const stationName = stationLabel(shift.station, locale);

  const lateArrivalTitle = shift.lateArrivalFlag
    ? `${dict.agents.lateArrivalBadge}${shift.lateArrivalMinutes ? ` (${shift.lateArrivalMinutes} min)` : ""}`
    : undefined;
  const alertTitle = shift.restViolationFlag
    ? dict.schedule.replacement.rejections.rest_violation
    : shift.overtimeFlag
      ? dict.schedule.replacement.rejections.weekly_hours_exceeded
      : undefined;

  return (
    <div
      className={cn(
        "group/chip card-lift relative overflow-hidden rounded-xl border px-2.5 py-2 text-xs shadow-xs",
        isAutopilot ? AUTOPILOT_CAPSULE : matrix.capsule,
        isDraft && !isAutopilot && "opacity-90",
        draggableHint && "ring-1 ring-foreground/10",
        compact && "py-1.5",
      )}
      title={`${shift.employee?.fullName ?? dict.calendar.unassigned} · ${formatTimeRange(shift.startsAt, shift.endsAt, locale)}${alertTitle ? ` · ${alertTitle}` : ""}`}
    >
      {isDraft && onDelete && (
        <button
          type="button"
          data-interactive
          onClick={(e) => {
            e.stopPropagation();
            onDelete();
          }}
          className="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-danger text-white opacity-0 shadow-sm transition-opacity hover:opacity-100 group-hover/chip:opacity-90"
          aria-label={dict.calendar.deleteDraftShift}
        >
          <X className="h-2.5 w-2.5" aria-hidden />
        </button>
      )}

      <div className="flex items-center gap-2">
        {!compact && (
          <UserAvatar
            fullName={shift.employee?.fullName ?? dict.calendar.unassigned}
            pictureUrl={shift.employee?.profilePictureUrl}
            stationColorHex={shift.station.colorHex}
            size="sm"
          />
        )}
        <div className="min-w-0 flex-1">
          <div className="flex items-center justify-between gap-1.5">
            <span
              className={cn(
                "truncate font-semibold leading-tight",
                unassigned && "italic opacity-80",
              )}
            >
              {shift.employee?.fullName ?? dict.calendar.unassigned}
            </span>
            <div className="flex shrink-0 items-center gap-0.5 opacity-80">
              {shift.isAutoGenerated && (
                <span title={dict.calendar.autoGenerated}>
                  <Sparkles className="h-3 w-3" aria-hidden />
                </span>
              )}
              {shift.lateArrivalFlag && (
                <span title={lateArrivalTitle}>
                  <Clock3 className="h-3 w-3 text-warning" aria-hidden />
                </span>
              )}
              {hasAlert && (
                <span title={alertTitle}>
                  <AlertTriangle className="h-3 w-3 text-warning" aria-hidden />
                </span>
              )}
              <PeriodIcon className={cn("h-3 w-3", period.text)} aria-hidden />
            </div>
          </div>

          {!compact && (
            <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
              <span
                className={cn(
                  "station-badge",
                  isAutopilot ? AUTOPILOT_BADGE : matrix.badge,
                )}
              >
                {isAutopilot ? "RSI" : stationName}
              </span>
              <span className="metric text-[11px] opacity-80">
                {formatTimeRange(shift.startsAt, shift.endsAt, locale)}
              </span>
            </div>
          )}

          {compact && (
            <div className="mt-0.5 flex items-center justify-between gap-1 opacity-80">
              <span className="metric text-[10px]">
                {formatTimeRange(shift.startsAt, shift.endsAt, locale)}
              </span>
              <span className={cn("text-[9px] font-bold uppercase tracking-wider", period.text)}>
                {dict.shiftPeriod[resolvedPeriod]}
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
