import "server-only";

import type { ShiftPeriod } from "@/generated/prisma/enums";
import { MIN_REST_HOURS } from "@/lib/agents/find-available-replacements";
import { asPlainNumber } from "@/lib/data/serialize";
import { prisma } from "@/lib/prisma";
import {
  computeRequiredHeadcountCurve,
  getStaffingProfilesForLocation,
} from "@/lib/scheduling/staffing-curve";

/** Durée maximale d'un quart généré automatiquement — au-delà, on découpe en plusieurs blocs. */
const MAX_SHIFT_HOURS = 8;
/** Heure de bascule DAY/NIGHT pour les quarts générés (heuristique simple). */
const NIGHT_PERIOD_HOUR = 17;

type CandidateMember = {
  userId: string;
  fullName: string;
  maxHoursPerWeek: number;
  availabilities: { dayOfWeek: number; startTime: string; endTime: string }[];
  timeOff: { startDate: Date; endDate: Date }[];
};

type ScheduledInterval = { start: Date; end: Date };

export type DraftShiftRow = {
  stationId: string;
  dayOffset: number;
  startsAt: Date;
  endsAt: Date;
  employeeId: string | null;
  employeeName: string | null;
};

export type DraftGenerationSummary = {
  weekStart: string;
  totalShifts: number;
  assignedShifts: number;
  unassignedShifts: number;
  totalHours: number;
  byStation: Array<{ stationId: string; generated: number; assigned: number }>;
};

/** Convertit une courbe d'effectif requis (24h) en blocs de quarts contigus — algorithme "layer peeling" classique de planification. */
export function generateShiftBlocksFromCurve(
  required: number[],
): Array<{ startHour: number; endHour: number }> {
  const remaining = [...required];
  const blocks: Array<{ startHour: number; endHour: number }> = [];
  let safety = 0;

  while (remaining.some((r) => r > 0) && safety < 200) {
    safety += 1;
    const start = remaining.findIndex((r) => r > 0);
    if (start === -1) break;

    let end = start;
    while (end < 24 && remaining[end] > 0) end += 1;

    const blockEnd = Math.min(end, start + MAX_SHIFT_HOURS);
    blocks.push({ startHour: start, endHour: blockEnd });
    for (let h = start; h < blockEnd; h += 1) remaining[h] -= 1;
  }

  return blocks;
}

function addDays(date: Date, days: number): Date {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + days);
  return copy;
}

function formatHm(date: Date): string {
  return `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
}

function toDateOnly(date: Date): Date {
  const copy = new Date(date);
  copy.setHours(0, 0, 0, 0);
  return copy;
}

/**
 * Génère un brouillon d'horaire pour une semaine (dimanche → samedi, aligné
 * sur le trigger CNESST) à partir des projections de ventes et des cibles de
 * dotation par station. Respecte disponibilités récurrentes, congés
 * approuvés, maximum d'heures et repos minimal de 32h (LNT) — les mêmes
 * règles que l'Agent de Crise, pour qu'un brouillon publié ne se heurte
 * jamais au blindage Postgres.
 */
export async function generateDraftScheduleForWeek(input: {
  locationId: string;
  weekStart: Date;
  createdById: string;
}): Promise<DraftGenerationSummary> {
  const { locationId, weekStart, createdById } = input;
  const weekStartAtMidnight = toDateOnly(weekStart);
  const weekEnd = addDays(weekStartAtMidnight, 7);
  const windowStart = addDays(weekStartAtMidnight, -3);
  const windowEnd = addDays(weekEnd, 3);

  const [{ stations, profiles }, projections, members, existingShifts] = await Promise.all([
    getStaffingProfilesForLocation(locationId),
    prisma.hourlySalesProjection.findMany({ where: { locationId } }),
    prisma.locationMember.findMany({
      where: { locationId, user: { role: "EMPLOYEE" } },
      include: {
        user: {
          include: {
            employeeProfile: {
              include: {
                availabilities: { where: { isRecurring: true } },
                timeOffRequests: { where: { status: "APPROVED" } },
              },
            },
          },
        },
      },
    }),
    prisma.shift.findMany({
      where: {
        locationId,
        employeeId: { not: null },
        status: { notIn: ["REJECTED"] },
        startsAt: { gte: windowStart, lt: windowEnd },
        NOT: { isAutoGenerated: true, status: "DRAFT", startsAt: { gte: weekStartAtMidnight, lt: weekEnd } },
      },
      select: { employeeId: true, startsAt: true, endsAt: true },
    }),
  ]);

  const stationIds = stations.map((s) => s.id);
  const projectionByDayHour = new Map<string, number>();
  for (const row of projections) {
    projectionByDayHour.set(`${row.dayOfWeek}-${row.hour}`, asPlainNumber(row.amount));
  }

  const membersByStation = new Map<string, CandidateMember[]>();
  for (const stationId of stationIds) membersByStation.set(stationId, []);
  for (const member of members) {
    const profile = member.user.employeeProfile;
    if (!profile) continue;
    membersByStation.get(member.stationId)?.push({
      userId: member.userId,
      fullName: member.user.fullName,
      maxHoursPerWeek: profile.maxHoursPerWeek,
      availabilities: profile.availabilities,
      timeOff: profile.timeOffRequests.map((t) => ({ startDate: t.startDate, endDate: t.endDate })),
    });
  }

  const intervalsByUser = new Map<string, ScheduledInterval[]>();
  const weeklyHoursByUser = new Map<string, number>();
  for (const shift of existingShifts) {
    if (!shift.employeeId) continue;
    const list = intervalsByUser.get(shift.employeeId) ?? [];
    list.push({ start: shift.startsAt, end: shift.endsAt });
    intervalsByUser.set(shift.employeeId, list);

    if (shift.startsAt >= weekStartAtMidnight && shift.startsAt < weekEnd) {
      const hours = (shift.endsAt.getTime() - shift.startsAt.getTime()) / (1000 * 60 * 60);
      weeklyHoursByUser.set(shift.employeeId, (weeklyHoursByUser.get(shift.employeeId) ?? 0) + hours);
    }
  }

  const blocksToSchedule: Array<{
    stationId: string;
    dayOffset: number;
    dayOfWeek: number;
    startsAt: Date;
    endsAt: Date;
  }> = [];

  for (let dayOffset = 0; dayOffset < 7; dayOffset += 1) {
    const dayDate = addDays(weekStartAtMidnight, dayOffset);
    const dayOfWeek = dayDate.getDay();
    const salesByHour = Array.from({ length: 24 }, (_, h) => projectionByDayHour.get(`${dayOfWeek}-${h}`) ?? 0);
    const requiredByStation = computeRequiredHeadcountCurve(salesByHour, stationIds, profiles);

    for (const stationId of stationIds) {
      const blocks = generateShiftBlocksFromCurve(requiredByStation[stationId] ?? []);
      for (const block of blocks) {
        blocksToSchedule.push({
          stationId,
          dayOffset,
          dayOfWeek,
          startsAt: new Date(dayDate.getTime() + block.startHour * 60 * 60 * 1000),
          endsAt: new Date(dayDate.getTime() + block.endHour * 60 * 60 * 1000),
        });
      }
    }
  }

  blocksToSchedule.sort((a, b) => a.startsAt.getTime() - b.startsAt.getTime());

  const draftRows: DraftShiftRow[] = [];

  for (const block of blocksToSchedule) {
    const pool = membersByStation.get(block.stationId) ?? [];
    const blockHours = (block.endsAt.getTime() - block.startsAt.getTime()) / (1000 * 60 * 60);
    const startHm = formatHm(block.startsAt);
    const endHm = formatHm(block.endsAt);
    const blockDateOnly = toDateOnly(block.startsAt);

    const ranked = pool
      .filter((member) => {
        const onApprovedLeave = member.timeOff.some(
          (t) => t.startDate <= blockDateOnly && t.endDate >= blockDateOnly,
        );
        if (onApprovedLeave) return false;

        const covered = member.availabilities.some(
          (a) => a.dayOfWeek === block.dayOfWeek && a.startTime <= startHm && a.endTime >= endHm,
        );
        if (!covered) return false;

        const currentWeeklyHours = weeklyHoursByUser.get(member.userId) ?? 0;
        if (currentWeeklyHours + blockHours > member.maxHoursPerWeek) return false;

        const intervals = intervalsByUser.get(member.userId) ?? [];
        const hasConflict = intervals.some(
          (iv) => iv.start < block.endsAt && iv.end > block.startsAt,
        );
        if (hasConflict) return false;

        const violatesRest = intervals.some((iv) => {
          if (iv.end <= block.startsAt) {
            return (block.startsAt.getTime() - iv.end.getTime()) / (1000 * 60 * 60) < MIN_REST_HOURS;
          }
          if (iv.start >= block.endsAt) {
            return (iv.start.getTime() - block.endsAt.getTime()) / (1000 * 60 * 60) < MIN_REST_HOURS;
          }
          return false;
        });
        if (violatesRest) return false;

        return true;
      })
      .sort((a, b) => {
        const hoursA = weeklyHoursByUser.get(a.userId) ?? 0;
        const hoursB = weeklyHoursByUser.get(b.userId) ?? 0;
        if (hoursA !== hoursB) return hoursA - hoursB;
        return a.fullName.localeCompare(b.fullName);
      });

    const chosen = ranked[0] ?? null;

    if (chosen) {
      const list = intervalsByUser.get(chosen.userId) ?? [];
      list.push({ start: block.startsAt, end: block.endsAt });
      intervalsByUser.set(chosen.userId, list);
      weeklyHoursByUser.set(chosen.userId, (weeklyHoursByUser.get(chosen.userId) ?? 0) + blockHours);
    }

    draftRows.push({
      stationId: block.stationId,
      dayOffset: block.dayOffset,
      startsAt: block.startsAt,
      endsAt: block.endsAt,
      employeeId: chosen?.userId ?? null,
      employeeName: chosen?.fullName ?? null,
    });
  }

  await prisma.$transaction([
    prisma.shift.deleteMany({
      where: {
        locationId,
        isAutoGenerated: true,
        status: "DRAFT",
        startsAt: { gte: weekStartAtMidnight, lt: weekEnd },
      },
    }),
    prisma.shift.createMany({
      data: draftRows.map((row) => {
        const hours = (row.endsAt.getTime() - row.startsAt.getTime()) / (1000 * 60 * 60);
        const period: ShiftPeriod = row.startsAt.getHours() < NIGHT_PERIOD_HOUR ? "DAY" : "NIGHT";
        return {
          locationId,
          stationId: row.stationId,
          period,
          employeeId: row.employeeId,
          createdById,
          startsAt: row.startsAt,
          endsAt: row.endsAt,
          breakMinutes: hours >= 5 ? 30 : 0,
          status: "DRAFT" as const,
          isAutoGenerated: true,
        };
      }),
    }),
  ]);

  const byStation = stationIds.map((stationId) => {
    const rows = draftRows.filter((r) => r.stationId === stationId);
    return {
      stationId,
      generated: rows.length,
      assigned: rows.filter((r) => r.employeeId).length,
    };
  });

  return {
    weekStart: weekStartAtMidnight.toISOString(),
    totalShifts: draftRows.length,
    assignedShifts: draftRows.filter((r) => r.employeeId).length,
    unassignedShifts: draftRows.filter((r) => !r.employeeId).length,
    totalHours: Math.round(
      draftRows.reduce((sum, r) => sum + (r.endsAt.getTime() - r.startsAt.getTime()) / (1000 * 60 * 60), 0) * 10,
    ) / 10,
    byStation,
  };
}
